name: attention_bn_rca
general: 
  usecudnn: true
  usecudnnbenchmark: true
  model_load: true
  model_save: true
  save_path: ./save

input: 
  batch_size: 16
  num_worker: 16
  shuffle: true
  aug: false

model:
  landmark: true
  type: LSTM
  front: RESNET
  input_dim: 256
  hidden_dim: 256
  num_class: 500
  num_lstm: 2
  seperate: rca

training:
  train: true
  max_epoch: 15
  start_epoch: 0
  stats_frequency: 50
  data_path: /home/deepuser/lrw_result
  learning_rate: 0.0003
  momentum: 0.
  weight_decay: 0.
  schedule:
  - 2
  - 4
  - 6
  - 8
  - 10
  lr_decay: 0.5

validation:
  validate: true
  data_path: /home/deepuser/lrw_result
  save_accuracy: true
  accuracy_path: ./
