name: attention_cbam_0.0006_0.00001
general: 
  usecudnn: true
  usecudnnbenchmark: true
  model_load: true
  model_save: true
  save_path: ./save

input: 
  batch_size: 16
  num_worker: 16
  shuffle: true
  aug: false
  landmark: true
  landmark_seperate: true

model:
  type: LSTM
  front: RESNET
  input_dim: 256
  hidden_dim: 256
  num_class: 500
  num_lstm: 2
  attention: cbam_lmk

training:
  train: true
  max_epoch: 15
  start_epoch: 0
  stats_frequency: 50
  data_path: /home/deepuser/lrw_result
  learning_rate: 0.0006
  momentum: 0.
  weight_decay: 0.00001
  schedule:
  - 3
  - 6
  - 9
  - 12
  - 15
  lr_decay: 0.5

validation:
  validate: true
  data_path: /home/deepuser/lrw_result
  save_accuracy: true
  accuracy_path: ./
