name: baseline_no_aug_coord
general: 
  usecudnn: true
  usecudnnbenchmark: true
  model_load: true
  model_save: true
  save_path: ./save

input: 
  batch_size: 16
  num_worker: 16
  shuffle: true
  aug: false

model:
  coord: true
  landmark: false
  type: LSTM
  front: RESNET
  input_dim: 256
  hidden_dim: 256
  num_class: 500
  num_lstm: 2

training:
  train: true
  max_epoch: 10
  start_epoch: 0
  stats_frequency: 50
  data_path: /home/deepuser/lrw_result
  learning_rate: 0.0001
  momentum: 0.
  weight_decay: 0.
  schedule:
  - 5
  lr_decay: 0.1
  landmarkloss: false

validation:
  validate: true
  data_path: /home/deepuser/lrw_result
  save_accuracy: true
  accuracy_path: ./