name: baseline_fpn
general: 
  usecudnn: true
  usecudnnbenchmark: true
  model_load: true
  model_save: true
  save_path: ./save

input: 
  batch_size: 16
  num_worker: 16
  shuffle: true
  aug: false
  landmark: false
  landmark_seperate: false

model:
  type: LSTM
  front: RESNET
  input_dim: 256
  hidden_dim: 256
  num_class: 500
  num_lstm: 2
  attention: false
  fpn: true

training:
  train: true
  max_epoch: 15
  stats_frequency: 50
  data_path: /home/sayduke/lrw_result
  learning_rate: 0.0006
  weight_decay: 0.000001
  schedule:
  - 3
  - 6
  - 9
  - 12
  - 15
  lr_decay: 0.5

validation:
  validate: true
  data_path: /home/sayduke/lrw_result
  save_accuracy: true
  accuracy_path: ./