name: baseline_no_aug
general: 
  usecudnn: true
  usecudnnbenchmark: true
  model_load: true
  model_save: true
  save_path: ./save

input: 
  batch_size: 32
  num_worker: 32
  shuffle: true
  aug: false

model:
  coord: true
  landmark: true
  type: LSTM
  input_dim: 256
  hidden_dim: 256
  num_class: 500
  num_lstm: 2

training:
  train: true
  max_epoch: 15
  start_epoch: 0
  stats_frequency: 500
  data_path: /home/deepuser/lrw_result
  learning_rate: 0.01
  momentum: 0.
  weight_decay: 0.
  schedule:
  - 5
  - 10
  lr_decay: 0.1
  aug: true

validation:
  validate: true
  data_path: /home/deepuser/lrw_result
  save_accuracy: true
  accuracy_path: ./