name: baseline
general: 
  usecudnn: true
  usecudnnbenchmark: true
  model_load: true
  save_path: ./save

input: 
  batch_size: 18
  num_worker: 18
  shuffle: true

model:
  coord: false
  landmark: false
  type: LSTM
  input_dim: 512
  hidden_dim: 512
  num_class: 500
  num_lstm: 2

training:
  train: true
  max_epoch: 15
  start_epoch: 0
  stats_frequency: 1000
  data_path: /udisk/pszts-ssd/AV-ASR-data/BBC_Oxford/lipread_mp4
  learning_rate: 0.003
  momentum: 0.9
  weight_decay: 0.0001
  schedule:
  - 5
  - 10
  lr_decay: 0.1

validation:
  validate: true
  data_path: /udisk/pszts-ssd/AV-ASR-data/BBC_Oxford/lipread_mp4
  save_accuracy: true
  accuracy_path: ./