name: baseline_no_aug_densenet
general: 
  usecudnn: true
  usecudnnbenchmark: true
  model_load: true
  model_save: true
  save_path: ./save

input: 
  batch_size: 8
  num_worker: 8
  shuffle: true
  aug: false

model:
  coord: false
  landmark: false
  type: LSTM
  front: DENSENET
  input_dim: 256
  hidden_dim: 256
  num_class: 500
  num_lstm: 2

training:
  train: true
  max_epoch: 15
  start_epoch: 0
  stats_frequency: 50
  data_path: /home/deepuser/lrw_result
  learning_rate: 0.0001
  momentum: 0.
  weight_decay: 0.
  schedule:
  - 8
  - 13
  lr_decay: 0.1

validation:
  validate: true
  data_path: /home/deepuser/lrw_result
  save_accuracy: true
  accuracy_path: ./